### ISSUE TITLE
The original code for the Heidelberg data processing

### ISSUE THREAD

**Issue by Bravo2333** [electronicvisions/lauscher#11]
Could I please obtain the original code for the Heidelberg data processing? The complex acoustic knowledge has taken up a lot of my time, yet I’m struggling to make progress.

**Comment by ystradmann** [comment]
Hi,

the content of this repository represents the original code that was used for the transformation from the Heidelberg Digit data set (HD) to the Spiking Heidelberg digit data set (SHD).
You will find the different acoustic transformations in [`lauscher/transformations/`](https://github.com/electronicvisions/lauscher/tree/master/lauscher/transformations). You will only need to look at these files if you intend to modify the algorithm.

Transforming a wave file into spikes is wrapped by a single command, [as indicated in the Readme](https://github.com/electronicvisions/lauscher/tree/master?tab=readme-ov-file#usage).
