### ISSUE TITLE
Convert multiple audio files

### ISSUE THREAD

**Issue by dramlanbasu** [electronicvisions/lauscher#12]
Please if it can be cleared on how to convert multiple audio files instead of doing the same one file at a time?

**Comment by ystradmann** [comment]
`lauscher` does not have intrinsic support for handling multiple files. You can, however, do so using your shell. For example
```bash
for file in …/*.flac; do
    output_file="${file%.flac}.npz"
    python -m lauscher "$file" "$output_file" --num_channels 70 --verbose
done
```
If you want to process multiple files in parallel, GNU's `parallel` can be an option. You will find documentation online.
